version: '3.9'

services:
  h200-serverless:
    build:
      context: .
      dockerfile: docker/Dockerfile.serverless
    image: ${DOCKER_USERNAME}/h200-mug-positioning:serverless-latest
    environment:
      - DEPLOYMENT_MODE=serverless
      - FLASHBOOT_ENABLED=true
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - REDIS_HOST=redis
    depends_on:
      - redis

  h200-timed:
    build:
      context: .
      dockerfile: docker/Dockerfile.timed
    image: ${DOCKER_USERNAME}/h200-mug-positioning:timed-latest
    environment:
      - DEPLOYMENT_MODE=timed
      - ENABLE_CONTROL_PLANE=true
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
