name: Deploy H200 Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          driver-opts: |
            cloud-token=${{ secrets.DOCKER_BUILD_CLOUD_TOKEN }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Get version
        id: version
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.serverless
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/h200-mug-positioning:serverless-latest
            ${{ secrets.DOCKER_USERNAME }}/h200-mug-positioning:serverless-${{ steps.version.outputs.VERSION }}
          platforms: linux/amd64

      - name: Deploy to RunPod
        env:
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
        run: |
          python scripts/deploy_to_runpod.py \
            --serverless-image ${{ secrets.DOCKER_USERNAME }}/h200-mug-positioning:serverless-${{ steps.version.outputs.VERSION }} \
            --timed-image ${{ secrets.DOCKER_USERNAME }}/h200-mug-positioning:timed-${{ steps.version.outputs.VERSION }} \
            --enable-r2 \
            --enable-redis
